Updating to 0.1.6 fdikbquery.
ABI-Software/data-portal pull request #42
Opened 2019-08-15 00:49 UTC by hsorby

Also includes some work on communicating with the oSPARC platform that is not quite finished.

2019-08-22 23:47 UTC, alan-wu commented
Will the testing get kicked off...?

2019-08-27 05:10 UTC, Tehsurfer commented
Is this algood to be included? I've started working on fdikbquery@0.1.6

2019-08-28 04:56 UTC, hsorby commented
I still have some changes pending before this gets merged.

2019-09-18 02:59 UTC, hsorby commented
This should be ready for testing now 👍

2019-09-18 22:45 UTC, alan-wu commented
Is fdikbquery0.1.6 the version to use for the latest changes?

2019-09-18 22:49 UTC, hsorby commented
Yes.

2019-09-18 23:02 UTC, alan-wu commented
Great, I will give it a try and update the UI tests if all is well.

2019-09-19 21:36 UTC, alan-wu requested changes

2019-09-19 21:36 UTC, alan-wu commented on map_core/app/src/main.js
> +let BFCSVExporterModule = require('mapcoreintegratedwebapp').BFCSVExporterModule;
This should not be changed.

2019-09-19 21:36 UTC, alan-wu commented on map_core/app/src/main.js
> +let BFCSVExporterDialog = require('mapcoreintegratedwebapp').BFCSVExporterDialog;
It has been renamed to PlotsvyDialog.

2019-09-19 21:36 UTC, alan-wu commented on map_core/app/src/main.js
> +      moduleManager.addConstructor("Data Viewer", BFCSVExporterModule, BFCSVExporterDialog);
Same as above.

2019-09-19 21:36 UTC, alan-wu commented on map_core/views.py
> +    print("response!!!!!!!")
Remove?

2019-09-19 21:36 UTC, alan-wu commented on map_core/app/src/main.js
> -			var options = {"url":url};
Keep this?

2019-09-19 21:36 UTC, alan-wu commented on map_core/app/src/main.js
> +      let data = tabManager.createDialog("Data Viewer");
Need the options.

2019-09-19 21:41 UTC, hsorby commented on map_core/views.py
> +    print("response!!!!!!!")
Not getting called yet still a work in progress.

2019-09-19 22:28 UTC, alan-wu commented
Looking good and merging that in. The UI testing will catch up with this revision.

2019-09-19 22:29 UTC, merged